# Generated by Django 4.1.2 on 2022-11-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0003_alter_user_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeproducts',
            name='id_product',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
