# Generated by Django 4.1.2 on 2022-11-18 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeddyBear', '0003_alter_products_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='curent_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='discount_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='hot_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='initial_price',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='ChildrentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TeddyBear.category')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='products',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='products',
            name='childrent_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TeddyBear.childrentcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='products',
            unique_together={('name', 'childrent_category')},
        ),
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.RemoveField(
            model_name='products',
            name='price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='products',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='products',
            name='type',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
