# Generated by Django 4.1.2 on 2022-11-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreManage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
