# Generated by Django 4.1.2 on 2022-11-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreManage', '0002_order_active_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproduct',
            old_name='customer_order',
            new_name='customer_orderId',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='product_code',
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='product_Id',
            field=models.IntegerField(default=0),
        ),
    ]
