# Generated by Django 4.1.2 on 2022-11-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreManage', '0004_cartproduct_create_date_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartproduct',
            options={'ordering': ['id', 'create_date_order']},
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='product_Id',
            field=models.CharField(max_length=20),
        ),
    ]
