# Generated by Django 4.1.2 on 2022-11-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreManage', '0005_alter_cartproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='product_Id',
            field=models.CharField(max_length=100),
        ),
    ]
