# Generated by Django 4.1.2 on 2022-11-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreManage', '0006_alter_cartproduct_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='create_date_order',
            field=models.CharField(max_length=100),
        ),
    ]
